services:
  postgres:
    image: postgres:13.3
    container_name: hite-database
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "release"
      POSTGRES_PASSWORD: "horse_ate_green_guinea_pig"
    volumes:
      - hite_postgres_data:/var/lib/postgresql/data  # Volume для хранения данных
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db", "-U", "release"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432" # проброшены для дебага и удобства разработки, на релизе убрать
    networks:
      - net_postgres
  backend-hite-baseline:
    container_name: hite-back-baseline
    depends_on:
      postgres:
        condition: service_healthy
    build: ./back-end/
    ports:
      - "8453:8453"
    networks:
      - net_postgres

networks:
  net_postgres:
    driver: bridge

volumes:
  hite_postgres_data: